import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e1e4",
        "primary-fixed-dim": "#c6c6c7",
        "surface-variant": "#353437",
        "secondary-container": "#45464e",
        "on-background": "#e5e1e4",
        "tertiary-fixed": "#ebe0dc",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed-variant": "#4c4543",
        "primary-container": "#e2e2e3",
        "primary-fixed": "#e2e2e3",
        "surface-dim": "#131315",
        "on-primary-container": "#636466",
        "on-primary-fixed": "#1a1c1d",
        "on-tertiary": "#352f2d",
        "inverse-primary": "#5d5e60",
        "on-secondary-fixed-variant": "#45464e",
        "on-secondary": "#2f3037",
        background: "#0a0a0c",
        primary: "#ffffff",
        "surface-container-high": "#2a2a2c",
        "on-secondary-fixed": "#1a1b22",
        "surface-container-highest": "#353437",
        error: "#ffb4ab",
        "on-tertiary-container": "#6a6360",
        "on-secondary-container": "#b4b4bd",
        "surface-bright": "#39393b",
        outline: "#8e9193",
        "on-error": "#690005",
        "outline-variant": "#27272a",
        "tertiary-fixed-dim": "#cec4c1",
        "secondary-fixed-dim": "#c6c6cf",
        "inverse-on-surface": "#313032",
        "surface-container": "#18181b",
        "surface-tint": "#c6c6c7",
        "inverse-surface": "#e5e1e4",
        "on-surface-variant": "#a1a1aa",
        "on-error-container": "#ffdad6",
        tertiary: "#ffffff",
        surface: "#121215",
        "on-primary": "#0a0a0c",
        "error-container": "#93000a",
        "tertiary-container": "#ebe0dc",
        "secondary-fixed": "#e2e1eb",
        "surface-container-low": "#131316",
        secondary: "#c6c6cf",
        "on-primary-fixed-variant": "#454748",
        "on-tertiary-fixed": "#1f1b18",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "auth-card-width": "380px",
        "space-3xl": "4.5rem",
        "space-xl": "2rem",
        "input-height": "44px",
        "space-sm": "0.75rem",
        "button-height": "44px",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        "body-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        display: ["var(--font-geist)", "Geist", "sans-serif"],
        "body-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "code-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "headline-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-md": ["var(--font-geist)", "Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "500" }],
        display: ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
